server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: serviceorder
  jackson:
    property-naming-strategy: SNAKE_CASE
    constructor-detector: default
  cloud:
    azure:
      compatibility-verifier:
        enabled: false
      keyvault:
        secret:
          property-sources[0]:
            name: key-vault-property-source-1
            endpoint: https://clavedesarrollo.vault.azure.net/
          property-source-enabled: true
      cosmos:
        database: ${basededatoscosmosdb}
        populate-query-metrics: true
        endpoint: ${endpoint-cosmos}
        key: ${urikeycosmo}
      servicebus:
        connection-string: ${connectionStringServiceBus}
        queue-name: "pedidos"

